---
- import_tasks: user.yml
  tags: [ letsencrypt, letsencrypt-acmesh, user ]

- import_tasks: install.yml
  tags: [ letsencrypt, letsencrypt-acmesh, install ]

- name: generate certificate (multiple)
  include: cert.yml
  with_items: "{{ letsencrypt_acmesh_certs }}"
  loop_control:
    loop_var: letsencrypt_acmesh_cert
  tags: [ letsencrypt, letsencrypt-acmesh, configure ]
