---
- include_tasks: user.yml
  tags: [ letsencrypt-acmesh, user ]

- include_tasks: install.yml
  tags: [ letsencrypt-acmesh, install ]

- name: generate certificate (multiple)
  include_tasks: cert.yml
  with_items: "{{ letsencrypt_acmesh_certs }}"
  loop_control:
    loop_var: letsencrypt_acmesh_cert
  tags: configure
