---
driver:
  name: docker
platforms:
  - name: ansible-role-letsencrypt-acmesh-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  options:
    vvv: true
#    tags: [ configure ]
  inventory:
    group_vars:
      all:
        letsencrypt_acmesh_env: "STAGE=1"
        letsencrypt_acmesh_email: admin@example.com
        letsencrypt_acmesh_certs:
          - domains: [ single.example.com ]
            args: "--dns dns_selectel"
          - domains: [ two.example.com, www.two.example.com ]
            args: "--dns dns_selectel"
          - domains: [ юникодный.рф, example.com ]
            args: "--dns dns_selectel"
          - domains: [ "*.example.com" ]
            args: "--dns dns_selectel"
